# Generated by Django 5.1.6 on 2025-03-10 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_input', models.CharField(choices=[('important', 'important'), ('not important', 'not important'), ('not sure', 'not sure')], default='not sure', max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.status'),
        ),
    ]
