# Generated by Django 5.1.6 on 2025-03-12 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_variation_variation_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variation_value_input',
            fields=[
                ('variation_value_id', models.AutoField(primary_key=True, serialize=False)),
                ('variation_value_value', models.CharField(max_length=15)),
                ('variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variation', to='api.variation')),
            ],
        ),
        migrations.DeleteModel(
            name='Variation_value',
        ),
    ]
