# Generated by Django 5.1.6 on 2025-03-12 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_variation_value_input_delete_variation_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='Variation_value_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.variation_value_input'),
        ),
    ]
