# Generated by Django 5.1.6 on 2025-03-12 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_todo_variation_value_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='Variation_value_input',
        ),
        migrations.AlterField(
            model_name='variation_value_input',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variation_name', to='api.variation'),
        ),
        migrations.AddField(
            model_name='todo',
            name='variation_value_input',
            field=models.ManyToManyField(blank=True, null=True, related_name='v_input', to='api.variation_value_input'),
        ),
    ]
