# Generated by Django 5.1.6 on 2025-03-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_todo_variation_value_input_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='variation_value_input',
            field=models.ManyToManyField(blank=True, related_name='v_input', to='api.variation_value_input'),
        ),
    ]
