# Generated by Django 5.1.6 on 2025-03-20 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_todo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
    ]
